language: c

matrix:
  include:
    - os: linux
      services:
        - docker
      script:
        - |
          bash -c "while true; do echo \$(date) - travis building ...; sleep 540; done" &
          export PING_LOOP_PID=$!
        - |
          cat <<-EOF | docker run -i ocaml/opam:ubuntu-16.04_ocaml-4.05.0 bash -
          set -e
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq && apt-get install -qq git curl m4
          opam install -y ocamlfind camlp5
          git clone https://github.com/asdf-vm/asdf.git
          . asdf/asdf.sh
          export ASDF_CONCURRENCY=4
          asdf plugin-test coq https://github.com/gingerhot/asdf-coq.git 'coqc -v'
          EOF
      after_script:
        - kill -9 $PING_LOOP_PID

    - os: osx
      before_script:
        - brew install aspcud
        - git clone https://github.com/asdf-vm/asdf.git
        - . asdf/asdf.sh
        - echo ". $PWD/asdf/asdf.sh" >> ~/.bash_profile
        - asdf plugin-add ocaml https://github.com/vic/asdf-ocaml.git
        - asdf install ocaml 4.06.0
        - asdf global ocaml 4.06.0
        - echo '. /Users/travis/build/gingerhot/asdf-coq/asdf/installs/ocaml/4.06.0/opam-init/init.sh > /dev/null 2> /dev/null || true' >> ~/.bash_profile
        - |
          echo 'let () =
                  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
                  with Not_found -> ()
                ;;' > ~/.ocamlinit
        - cat ~/.bash_profile
        - opam install -y ocamlfind camlp5
        - asdf reshim ocaml
        - cat ~/.bash_profile
        - export ASDF_CONCURRENCY=4
      script:
        - |
          bash -c "while true; do echo \$(date) - travis building ...; sleep 540; done" &
          export PING_LOOP_PID=$!
        - ls /Users/travis/build/gingerhot/asdf-coq/asdf/shims
        - export CAMEL_PATH="/Users/travis/build/gingerhot/asdf-coq/asdf/installs/ocaml/4.06.0/4.06.0/bin"
        - export PATH="$CAMEL_PATH:$PATH"
        - export COQ_EXTRA_CONFIGURE_OPTIONS="-camldir $CAMEL_PATH"
        - asdf plugin-test coq https://github.com/gingerhot/asdf-coq.git 'coqc -v'
      after_script:
        - kill -9 $PING_LOOP_PID
