language: generic

script: asdf plugin-test coq https://github.com/gingerhot/asdf-coq.git "coqc -v"

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - asdf plugin-add ocaml
  - |
      if [ $(uname) == "Darwin" ]; then brew install aspcud; else echo "This's a Linux!"; fi
  - asdf install ocaml 4.06.0
  - |
      if [ $(uname) == "Darwin" ]; then eval `opam config env --root=/Users/travis/build/gingerhot/asdf-coq/asdf/installs/ocaml/4.06.0`; else eval `opam config env --root=/home/travis/build/gingerhot/asdf-coq/asdf/installs/ocaml/4.06.0`; fi
  - asdf global ocaml 4.06.0
  - opam install -y ocamlfind camlp5
  - asdf reshim ocaml

os:
  - linux
  - osx
