language: generic

matrix:
  include:
    - os: linux
      services:
        - docker
      script:
        - |
          bash -c "while true; do echo \$(date) - travis building ...; sleep 540; done" &
          export PING_LOOP_PID=$!
        - |
          cat <<-EOF | docker run -i ocaml/opam:ubuntu-16.04_ocaml-4.05.0 bash -
          set -e
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq && apt-get install -qq git curl m4
          opam install -y ocamlfind camlp5
          git clone https://github.com/asdf-vm/asdf.git
          . asdf/asdf.sh
          asdf plugin-test coq https://github.com/gingerhot/asdf-coq.git 'coqc --help'
          EOF
      after_script:
        - kill -9 $PING_LOOP_PID

    - os: osx
      before_script:
        - brew install ocaml opam
        - opam init
        - eval `opam config env`
        - opam install -y ocamlfind camlp5
        - git clone https://github.com/asdf-vm/asdf.git
        - . asdf/asdf.sh
      script:
        - |
          bash -c "while true; do echo \$(date) - travis building ...; sleep 540; done" &
          export PING_LOOP_PID=$!
        - asdf plugin-test coq https://github.com/gingerhot/asdf-coq.git 'coqc --help'
      after_script:
        - kill -9 $PING_LOOP_PID
